const actionTypes = {
  ADD_PERSON: 'ADD_PERSON',
  ADD_PERSON_SUCCESS: 'ADD_PERSON_SUCCESS',
  DELETE_PERSON: 'DELETE_PERSON',
  MODIFY_PERSON: 'MODIFY_PERSON',
  SHOW_MODAL: 'SHOW_MODAL',
  HIDE_MODAL: 'HIDE_MODAL'
};
export { actionTypes };
